readmeio/syntax-highlighter

package.json
src/codeEditor/index.jsx
src/codeMirror/index.jsx
src/index.js
src/index.node.js
src/utils/cm-mode-imports.js
src/utils/modes.js
webpack.config.js

- Exposing `modes` and `getMode` as core exports
- Separating client and server builds for specific usage
- Only exposing server-compatible resources to server build
Provide as much information as you can on how to test what you've done.

fix(bundle): client and server compatibility

---

public/index.js
src/codeMirror/index.jsx
src/index.js

Attempting to minimize potential provider instances, mirroring our markdown lib implementation. This fix is targeting an issue where provider seeded data does not get passed correctly to the consumer scope.
Running this locally will display variable consumption.

feat(context): exporting context provider

---

package-lock.json
package.json

https://stackoverflow.com/questions/30451556/what-is-the-correct-way-of-adding-a-dependency-to-react-in-your-package-json-for

chore: moving react and react-dom into being peerdeps

---

__tests__/codeMirror.test.js
src/codeMirror/index.jsx

[Asana Ticket](https://app.asana.com/0/1177736375805705/1198569009223205) 
For every language except node, putting in an empty line will cause two empty lines to show up in readOnly mode. This seems to be caused when the if and then else statements are hit on consecutive newline characters
change the code string in public/index.js to one of the following:
`CURL *hnd = curl_easy_init();\n\ncurl_easy_setopt(hnd, CURLOPT_CUSTOMREQUEST, "GET");\n\ncurl_easy_setopt(hnd, CURLOPT_URL, "http://httpbin.orgpet/");\n\nCURLcode ret = curl_easy_perform(hnd);`, 'c'
`import requests\n\nurl = "http://httpbin.orgpet/"\n\nresponse = requests.request("HEAD", url)\n\nprint(response.text) `, 'python'

fix: check for \n in CodeMirror runmode

---

src/codeMirror/index.jsx

Previous fix brought in `newline` regexp check in our `codeMirror.runmode()` call. This could potentially lead to some side-effects that were not planning for. Updating this logic to check for our `opt.highlightMode` flag as well.

fix: isolating regex check to highlightmode option

---

public/index.js
src/codeEditor/index.jsx
src/codeEditor/style.scss
src/codeMirror/index.jsx
src/codeMirror/style.scss
src/index.js

Adds support for light theme (Neo); which is the same theme we use in the dash.

feat(themes): add support for a light theme

---

public/index.js
src/codeEditor/index.jsx
src/index.js

https://github.com/readmeio/syntax-highlighter/pull/38 removed support for `tomorrow-night` on non-editable instances of this library, this adds support for a new `customTheme` parameter to bring it back.

feat: adding support for custom themes

---

__tests__/__snapshots__/codeMirror.test.js.snap
__tests__/codeMirror.test.js
package-lock.json
package.json
src/codeMirror/index.jsx

ReadMe user variables are written like `<<var>>`. Depending on the
language parser used by CodeMirror, that could get parsed into
multiple tokens, ie [`<<`, `var`, `>>`]. So, we do a first pass to
remove the variables. And reinsert them after CodeMirror has done its
parsing.
This PR also fixes inserting multiple variables per line.
The following would not get interpolated:
```js
const foo = <<name>>;
```
Multiple variables (previously, only the second would get interpolated):
```js
const foo = { bar: <<name>>, baz: <<name>> };
```
[[bare variable ticket]](https://app.asana.com/0/1199089258199423/1198973877710478/f)
[[multiple variable ticket]](https://app.asana.com/0/1178132843162889/1179842282864914/f)

fix: allow for bare variable substitution

---

__tests__/codeMirror.test.js
package-lock.json
package.json
webpack.config.js

This sets `@readme/variable` as a peerDep. Variable is using a context
to propagate user variables. So, it needs to be a singleton in the app,
otherwise any imported consumers won't be matched the correct provider.

chore(deps): set variable as a peerDep

---

src/index.js

To allow us to pass in classnames so we can style overflow for readonly. https://github.com/readmeio/ui/pull/468

feat(syntax-highlighter): support classname

---

__tests__/codeMirror.test.js
src/codeMirror/index.jsx

I'm noticing a weird issue in the recipes modals where JSON response bodies like this:
```json
{"success":true}
```
would drop the closing bracket for some reason, so it'd render
```json
{"success":true
```
I isolated it down to an issue with the `<StyledSyntaxHighlighter />` component and created a test to account for this edge case.
If CI passes, we should be good!

fix: closing bracket in json with highlightMode enabled

---

src/codeMirror/style.scss

Don't highlight the entire code sample on hover. Fixes RM-209
https://linear.app/readme-io/issue/RM-209/🙅🏻‍♂️-highlighting-flashes

feat(recipes): don't highlight everything on hover

---

src/codeMirror/style.scss

Won't dim code if .CodeEditor also has .CodeEditor-Input_highlight (you can test this by manually adding the class)
Provide as much information as you can on how to test what you've done.

style(codemirror): add highlight class

---

package.json

Just like I did with https://github.com/readmeio/markdown/pull/131, this loosens up our peerDep requirement on `@readme/variable`.

fix: loosen up our @readme/variable peerDep requirement

---

README.md

Update docs to include `customTheme`

docs: add custom theme to available option docs

---

README.md
src/index.js

See: [@readme/markdown#140][140]
:---:
If you write a code block, the RDMD engine will wrap the code contents with a `div`. Unfortunately, this holds true for *inline* code snippets as well, since they're represented by the same underlying MDAST. [Per the W3][w3], `<p>` tags may *only* contain other inline elements, which means the engine throws a warning whenever we render an inline code snippet within a paragraph. Which is, like, all the time...
Check out [@readme/markdown#140][140] for the integration piece of this puzzle.
[w3]: https://www.w3.org/TR/html401/struct/text.html#h-9.3.1
[140]: https://github.com/readmeio/markdown/pull/140

chore(options): add a new inline toggle

---

__tests__/__snapshots__/codeMirror.test.js.snap
__tests__/codeMirror.test.js
public/index.js
src/codeEditor/style.scss
src/codeMirror/index.jsx
src/index.js

This enables the user to pass `foldGutter: true` into the options for the `syntaxHighlighter` which will return a component that support code folding that uses the same CodeMirror add-on as is show in this [demo](https://codemirror.net/demo/folding.html).
This change can be tested on `http://localhost:3400/`, here is a screen recording:
https://user-images.githubusercontent.com/4505008/113056084-59e23780-9179-11eb-8d1a-1d3ec39d4d71.mov

feat: enable code folding

---

.github/workflows/bundlewatch.yml
.github/workflows/ci.yml
package-lock.json
package.json

Installing `@readme/syntax-highlighter` in `@readme/markdown` now causes it to install an old version of the Markdown library there, which 🙃 .
Since we're using NPM 7 for most everything now and that installs peerDeps by default, we can remove `@readme/markdown` as being a devDep (which we were using because peerDeps weren't installed by default).

chore: removing @readme/markdown as a devDep

---

__tests__/__snapshots__/codeMirror.test.js.snap
package-lock.json
package.json

We're currently having Webpack issues with releases of Codemirror past 5.54.0 so we're temporarily pinning back `codemirror` and `codemirror-graphql` to releases that we know worked previously.
Since the places where we're having issues with it will be going away when we fully deprecate Hub 2 at the end of the year we should be able to bump these back up sometime in January or February.

fix: pinning codemirror to 5.54.0

---

public/index.js
src/codeMirror/index.jsx
src/codeMirror/style.scss

| 🎫 Fix CX-227 |
| :------------ |
Non-trackpad users have been having struggling to scroll our code blocks horizontally. This might help:
If you pull this branch down and run `start`, you should see some very subtle, simple overlay scrollbars.
[addon]: https://codemirror.net/5/demo/simplescrollbars.html

style: custom scrollbars

---

__tests__/codeMirror.test.js
src/codeMirror/index.jsx

| 🚥 Resolves CX-138 |
| :----------------- |
This PR prevents rendering escaped variables.
Consider the following markdown:
````
```
somebash \<< not a var >> log.txt
```
````

fix: dont variable-ize escaped sequences

---

__tests__/codeMirror.test.js
jest.config.js
package-lock.json
package.json
src/codeMirror/index.jsx
src/index.js

| 🚥 RM-9849 |
| :--------- |
Adds support for mdx style variables

feat: mdx vars
